### ISSUE TITLE
Can one compose lux layers with graph neural network

### ISSUE THREAD

**Issue by jakubMitura14** [avik-pal/Lux.jl#102]
Can one compose lux layers with graph neural network.

For flux there is geometric flux, but composing lux and flux is sth to be avoided 

 Or alternatively can one build a model in lux and incorporate it as a part of flux chain , to compose it with flux geometric

**Comment by jakubMitura14** [comment]
I need to experiment more

**Comment by MilkshakeForReal** [comment]
GeometricFlux is heavily flawed and I wouldn't recommend anyone to use it. You can see how my package [NeuralGraphPDE](https://github.com/MilkshakeForReal/NeuralGraphPDE.jl) defines a graph neural network, it's very simple

**Comment by jakubMitura14** [comment]
Fantastic thank you !
