### ISSUE TITLE
add OrdinaryDiffEq downstream test

### ISSUE THREAD

**Issue by vpuri3** [avik-pal/Lux.jl#110]
https://github.com/vpuri3/PDEInterfaces.jl/blob/ceb3ab1529cb5f3c30258ae2da5d4b968d6ef97c/examples/ad/ooo.jl#L1-L96

**Comment by avik-pal** [comment]
What do you mean? `OrdinaryDiffEq.jl` has nothing to do with Neural Networks.

**Comment by MilkshakeForReal** [comment]
That example should just would now with the newest version of `ComponentArrays`. Can you check it out?

**Comment by vpuri3** [comment]
it does work, thank you. i guess such cases will be tested when DiffEqFlux's GPU tutorials move to Lux.
