### ISSUE TITLE
Support for multidimensional data?

### ISSUE THREAD

**Issue by jakubMitura14** [avik-pal/Lux.jl#123]
Hello I have multidimensional (3 and 4 dims) data and flattening them is not an option but layers like dense seem to accept only 1 or 2D input. Am I correct or I am missing something?

Thanks For response !

**Comment by lungd** [comment]
Dense does support input arrays of arbitrary sizes by reshaping the input and the result (e.g. https://github.com/avik-pal/Lux.jl/blob/main/src/layers/basic.jl#L650)

```
julia> using Lux, Random

julia> d = Dense(1,2)
Dense(1 => 2)       # 4 parameters

julia> ps, st = Lux.setup(Random.default_rng(), d);

julia> x = randn(1,2,3,4,5);

julia> size(d(x, ps, st)[1])
(2, 2, 3, 4, 5)
```

**Comment by jakubMitura14** [comment]
Ok I was refering to this in documantation
```
nput

x must be a Matrix of size in_dims × B or a Vector of length in_dims
```

Thank You for fast response !!

**Comment by avik-pal** [comment]
Thanks for pointing it out. Fixed docs in #124.

**Comment by jakubMitura14** [comment]
Happy to help @avik-pal  , generally with so huge speed of development like is present in this repository it is fully understendable !

just checking Lux.Conv has
```
Image data should be stored in WHCN order (width, height, channels, batch)
```
so it is truly conv2D only - hence no possibility of 3d convolutions at the moment ?

**Comment by avik-pal** [comment]
No, it works for 3d see the inputs section. It is mentioned as an example of data ordering.

**Comment by jakubMitura14** [comment]
ok, fantastic ! so in this case  it can be  written
```
(width, height, channels, batch) 
or (width, height,depth, channels, batch)
```
