### ISSUE TITLE
checkpointing for backpropagation

### ISSUE THREAD

**Issue by jakubMitura14** [avik-pal/Lux.jl#139]
Hello is it possible to apply checkpointing in backpropagation - I mean recomputing output of some layers instead of saving them in order to reduce memory consumption during backpropagation.

Something like in https://fluxml.ai/Zygote.jl/dev/adjoints/#Checkpointing-1

**Comment by avik-pal** [comment]
Lux is mostly AD Agnostic, so yes you should be able to use checkpointing with the exact code that is present in Zygote documentation.
