### ISSUE TITLE
How to avoid the activation function conversion

### ISSUE THREAD

**Issue by IlyaOrson** [avik-pal/Lux.jl#152]
If I initialize a model with `tanh` activations they get autoconverted to `tanh_fast` which causes problems for my application.

```julia
Chain(
  Dense(2, layer_size, tanh; init_weight=Lux.glorot_normal),
  Dense(layer_size, 1, identity; init_weight=Lux.glorot_normal)
)
```

```julia
Chain(
    layer_1 = Dense(2 => 4, tanh_fast),  # 12 parameters
    layer_2 = Dense(4 => 1),            # 5 parameters
)         # Total: 17 parameters,
          #        plus 0 states, summarysize 32 bytes.
```

Can I avoid the automatic conversion? For now I use an anonymous functions which seem to work.

**Comment by avik-pal** [comment]
Currently, an anonymous function is the only way to do so. Though, we could add a kwarg to disable this transformation.

**Comment by avik-pal** [comment]
Starting `v0.4.23`, `allow_fast_activation=false` will prevent the `NNlib.fast_act(...)` conversion.
