### ISSUE TITLE
`] add Lux` doesn't work

### ISSUE THREAD

**Issue by ziyiyin97** [avik-pal/Lux.jl#19]
Just a kind reminder that the installation command `] add Lux` doesn't work

**Comment by ziyiyin97** [comment]
(@v1.7) pkg> add Lux
ERROR: The following package names could not be resolved:
 * Lux (not found in project, manifest or registry)

**Comment by avik-pal** [comment]
Yes I have been waiting for https://github.com/JuliaRegistries/General/pull/59605 to get merged

**Comment by avik-pal** [comment]
Should be fixed now
