### ISSUE TITLE
How to create a chain of LSTMcells in Lux.jl?

### ISSUE THREAD

**Issue by luboshanus** [avik-pal/Lux.jl#239]
Hi, 

could anyone provide a similar example in Lux.jl to this Flux classifier example below:
```Julia
# Seq2Many network
struct Seq2Many
    rnn # Recurrent layers
    fc  # Fully-connected layers
end

rnn = Chain(Dense(in_dim => nodes), Dropout(0.2f0), LSTM(nodes => nodes))
nn = Dense(nodes => out_dim, sigmoid))
# Make full Seq to Many
model = Seq2Many(rnn, nn)

# then make it trainable... etc.
```

Is there a way for **multiple layers of LSTM in Lux.jl** constructed in the way as it is in the examples? 
https://github.com/avik-pal/Lux.jl/blob/main/examples/SimpleRNN/main.jl

Thanks!

**Comment by avik-pal** [comment]
Closing since the OP's answer is the correct solution. Also for future reference there are utility layers like https://lux.csail.mit.edu/dev/api/layers/#Lux.StatefulRecurrentCell and https://lux.csail.mit.edu/dev/api/layers/#Lux.Recurrence which make handling RNNs in Chain easier.
