### ISSUE TITLE
Constrain the output layer!

### ISSUE THREAD

**Issue by aelmokadem** [avik-pal/Lux.jl#242]
Hi,

I was wondering if there is a way to integrate prior knowledge to the output layer of the NN, like constraints or penalties?

Thanks.

**Comment by avik-pal** [comment]
It would help if you were a bit more specific about the problem. For hard constraints, the easiest way is to reparameterize the outputs. For soft constraints, simple regularization might work out.

**Comment by aelmokadem** [comment]
Thanks @avik-pal  A simple specific example might be if I want to create a NN like 
```
NN = Lux.Chain(
    Lux.Dense(3, 16, relu), # hidden layer
    Lux.Dense(16, 2, relu) # output layer
)
```
I would need the first output to be constrained between 1-10 and the second to be centered around 2 ?!

**Comment by avik-pal** [comment]
You could use `tanh` activation and scale the values to be in 1-10 and for centered around 2, you can normalize and add 2

**Comment by aelmokadem** [comment]
Apologies for my technical difficulties here but could you point me to an example code that would do something like that?

**Comment by avik-pal** [comment]
```julia
NN = Chain(
    Dense(3, 16, tanh), x -> x .* 4.5f0 .+ 5.5f0,
    Dense(16, 2), x -> x ./ mean(x, dims=1) .+ 2.0f0
)
```

**Comment by aelmokadem** [comment]
@avik-pal  great. Thanks so much for your help.
