### ISSUE TITLE
On using ComponentArray for L2 regularization

### ISSUE THREAD

**Issue by srikumarks** [avik-pal/Lux.jl#243]
When including an L2 regularization term in my loss function, I find myself unable to use `ComponentArray` for the task because Zygote fails with it. My NN is pretty simple (shallow with only Dense layers). Here is a simple case that reproduces the error -

```julia
using Lux, Zygote, Random
nn = Chain(Dense(4,3),Dense(3,2))
rng = MersenneTwister(1234)
p, st = Lux.setup(rng,nn)
f(p) = sum(Array(ComponentArray(p)).^2)
println(f(p)) # Succeeds
gradient(f, p) # Fails with "ERROR: Mutating arrays is not supported -- called push!(Vector{Any}, ...)"
```

Just so this doesn't become an [XY problem](https://en.wikipedia.org/wiki/XY_problem), the main thing I'm trying to accomplish is to include an L2 regularization term in my loss function. One way to do it would be to pick out the parameters from the p nested tuple. `ComponentArray` would be a convenient way to collect them all together in one step, and so I tried it.

**Comment by avik-pal** [comment]
An easy way to implement it is:

```julia
f2(x::AbstractArray) = sum(x)
f2(x::Union{NamedTuple, Tuple}) = sum(f2, values(x))

gradient(f2, p) 
```

**Comment by YichengDWu** [comment]
You can add a chain rule for the constructor `ComponentArray(nt::NamedTuple)`. 

```julia
using ComponentArrays
using ChainRulesCore
ChainRulesCore.rrule(::Type{ComponentArray}, nt::NamedTuple) = ComponentArray(nt), Δ->(ChainRulesCore.NoTangent(), NamedTuple(Δ))

using Lux, Zygote, Random
nn = Chain(Dense(4,3),Dense(3,2))
rng = MersenneTwister(1234)
p, st = Lux.setup(rng,nn)
 f(p) = sum(abs2 , ComponentArray(p))
gradient(f, p)
```

**Comment by avik-pal** [comment]
Thanks @YichengDWu, for the patch. It should go into CA.jl but in the meantime I will add in the lux extensions
