### ISSUE TITLE
Hope to add more examples

### ISSUE THREAD

**Issue by zsz00** [avik-pal/Lux.jl#25]
Examples is the core of Lux.jl ecosystem 

Hope to add more examples:
1. As an example codes to study
2. Demonstrate the power and ease of use of Lux
3. Attract users and developers

Hope to refactor some examples use Lux.jl in  https://github.com/FluxML/model-zoo

such as:
[conv_mnist](https://github.com/FluxML/model-zoo/tree/master/vision/conv_mnist)
[vgg_cifar10](https://github.com/FluxML/model-zoo/tree/master/vision/vgg_cifar10)
ObjectDetector
GraphNeuralNetworks
Transformer
ViT
......

**Comment by MilkshakeForReal** [comment]
We don't have a GNN framework based on Lux yet

**Comment by avik-pal** [comment]
I am closing this issue because it is not actionable. If you want to add examples/tutorials, please go ahead and open PRs, no need to explicitly open issues.
