### ISSUE TITLE
Available architectures

### ISSUE THREAD

**Issue by gdalle** [avik-pal/Lux.jl#34]
Hi there, and congrats on what looks like a serious challenger to Flux!
I just saw the release of the model weights and I was wondering where to find predefined architectures, not necessarily with their weights. A quick scan of the docs didn't give me the answer but I might have missed it

**Comment by avik-pal** [comment]
Yeah the architectures have not yet been released. But hopefully soon, once I am able to evaluate the models https://github.com/avik-pal/Lux.jl/pull/29

**Comment by avik-pal** [comment]
Available on `main`. Will be available on the registry very soon (3 days)

**Comment by gdalle** [comment]
Awesome!
