### ISSUE TITLE
Quickstart Example: `using Optimisers, Zygote` do not work unless we explicitly add those to current environment.

### ISSUE THREAD

**Issue by Karthik-d-k** [avik-pal/Lux.jl#75]
Hi @avik-pal, Firstly, thanks for the great work that you are putting into this Library :)

## Issue: 
I'm new to `Lux.jl`, so i tried the Quick start example in [my Colab NB](https://colab.research.google.com/drive/1WYXzDvesFlDYYrbRgHvozsMxGineV7iy?usp=sharing) and found out that even though `Lux` installs `Optimisers` and `Zygote` packages, we cannot directly use (as per Quickstart example) -->
```julia
using Optimisers, Zygote
``` 
we get **Package not found** error.

## Workaround:
First we have to add both packages explicitly -->
 ```julia
Pkg.add(["Optimisers", "Zygote"])
```
though this won't install the packages again, instead it will reuse the installed packages (done during Lux installation) with the advantage of name spacing directly like below --> 
```julia
using Optimisers, Zygote
```
Or else we would have to namespace like this (i suppose) --> 
```julia
using Lux.Optimisers, Lux.Zygote
``` 

As this example is the first thing most people tries to run who are new to Lux, i thought i would bring up this issue.
 
**P.S**:  I only tried this on Colab, not locally.

**Comment by avik-pal** [comment]
```julia
Pkg.add(["Optimisers", "Zygote"])
```
is the correct way to do it. 

```julia
using Lux.Optimisers, Lux.Zygote
```
will work but the dependency is not a hard one and is not documented. So it can be dropped without any deprecation warning.

**Comment by Karthik-d-k** [comment]
> is the correct way to do it.

Thanks for confirming 👍
Shall i make a PR adding this ?

> So it can be dropped without any deprecation warning.

Sorry, i don't understand what you meant here !!

**Comment by avik-pal** [comment]
>  Shall i make a PR adding this ?

Sure go ahead. Though add it in a `!!! tip` box instead fo the code block

> Sorry, i don't understand what you meant here !!

If you use the functionality as `using Lux.Optimisers` and it works in `v0.4.6`, there is no guarantee that it will continue to work in `v0.4.7` or beyond since this is undocumented

**Comment by Karthik-d-k** [comment]
> Sure go ahead. Though add it in a !!! tip box instead fo the code block

Sure, will do it as u suggested.

> If you use the functionality as `using Lux.Optimisers` and it works in `v0.4.6`, there is no guarantee that it will continue to work in `v0.4.7` or beyond since this is undocumented

Now, it is completely clear 👍
