### ISSUE TITLE
[Feature request] Another type of `Chain` that sequentially passing `x` and `st`

### ISSUE THREAD

**Issue by MilkshakeForReal** [avik-pal/Lux.jl#96]
I'd like to have something similar to the current `Chain`, where the layers wrapped in it share the same states, and `applychain` would sequentially pass both the input and `st`.

**Comment by avik-pal** [comment]
But what does that mean? states and parameters are properties of individual layers. Do you have a specific example usecase in mind?

**Comment by MilkshakeForReal** [comment]
My initial idea was a bit less mature. A better way to put it I would like to have block-wise states, where layers inside a block can access them.

**Comment by MilkshakeForReal** [comment]
This doesn't sound general enough, but I don't know how to implement it with the current tools. `AbstractExplicitContainerLayer` seems to only allow me to initialize states for each layer. Graph neural networks are a good example. Many graph convolution layers work on the same graph, and my current practice is to initialize duplicate graphs for each layer. But if I want each layer change to the graph and pass it to the next layer I'm in trouble...

**Comment by avik-pal** [comment]
That seems like a very special case, where it would make sense to have such a layer, but I don't think it makes sense to put that here.

**Comment by MilkshakeForReal** [comment]
Yes, I will write a custom Chain to synchronize the `st` of each layer, thanks for the reply
